version: '3.8'

services:
  gazebo_gui:
    image: gazebo:latest
    platform: linux/amd64
    container_name: paris_swarm_gazebo_gui
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - GAZEBO_MODEL_PATH=/workspace/quadcopter_models:/workspace/paris_environment
    volumes:
      - ./paris_environment:/workspace/paris_environment:ro
      - ./quadcopter_models:/workspace/quadcopter_models:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - "11347:11345"
      - "11348:11346"
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
    networks:
      - paris_swarm_network
    restart: unless-stopped
    command: gazebo --verbose /workspace/paris_environment/worlds/paris_visual_world.world

networks:
  paris_swarm_network:
    external: true